# Generated by Django 2.1.5 on 2019-02-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activityinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateField(auto_now_add=True)),
                ('end_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Check_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Emotioninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awake', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(max_length=300)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('efficient', models.CharField(max_length=30)),
                ('belief', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Init_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('touxiang', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relax_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Report_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speechinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('label', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('touxiang', models.CharField(max_length=200)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='speechinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='report_situation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='relax_situation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='init_situation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='emotioninfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='course_situation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='check_situation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
        migrations.AddField(
            model_name='activityinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo'),
        ),
    ]
