# Generated by Django 2.1.5 on 2019-03-06 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0002_auto_20190306_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='touxiang',
            new_name='portrait',
        ),
    ]
