# Generated by Django 2.1.5 on 2019-03-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0003_auto_20190306_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotioninfo',
            old_name='content',
            new_name='contentb',
        ),
        migrations.AddField(
            model_name='emotioninfo',
            name='activity',
            field=models.CharField(default='Null', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotioninfo',
            name='contenta',
            field=models.CharField(default='Null', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotioninfo',
            name='contentm',
            field=models.CharField(default='Null', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotioninfo',
            name='mind',
            field=models.CharField(default='Null', max_length=300),
            preserve_default=False,
        ),
    ]
