# Generated by Django 2.1.7 on 2019-03-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0004_auto_20190318_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mingxianginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mingxiang_type', models.CharField(max_length=50)),
                ('mingxiang_start', models.DateTimeField()),
                ('mingxiang_end', models.DateTimeField()),
                ('mingxiang_response', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='check_situation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='activity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='belief',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='contenta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='contentb',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='contentm',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='mind',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report_situation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='speechinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
