# Generated by Django 2.1.5 on 2019-03-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0004_auto_20190318_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotioninfo',
            name='activity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='belief',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='contenta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='contentb',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='contentm',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='mind',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
