# Generated by Django 2.1.5 on 2019-03-20 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0005_auto_20190320_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mingxianginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mingxiang_type', models.CharField(max_length=50)),
                ('mingxiang_start', models.DateTimeField()),
                ('mingxiang_end', models.DateTimeField()),
                ('mingxiang_response', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='activityinfo',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='check_situation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emotioninfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report_situation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='speechinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
