# Generated by Django 2.1.7 on 2019-04-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0006_auto_20190331_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinioninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo')),
            ],
        ),
    ]
