# Generated by Django 2.1.7 on 2019-04-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0007_opinioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinioninfo',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
