# Generated by Django 2.1.7 on 2019-07-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0008_opinioninfo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_situation',
            name='text',
        ),
        migrations.AddField(
            model_name='report_situation',
            name='test_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
