# Generated by Django 2.1.7 on 2019-07-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0009_auto_20190713_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('test_grade', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psybot.Userinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='report_situation',
            name='test_grade',
        ),
        migrations.AddField(
            model_name='report_situation',
            name='text',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
