# Generated by Django 2.1.7 on 2019-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0010_auto_20190713_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_situation',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
