# Generated by Django 2.2.6 on 2019-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0011_auto_20190713_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hashid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
