# Generated by Django 2.2.7 on 2020-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0012_userinfo_hashid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinioninfoForSRT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
