# Generated by Django 2.2.6 on 2019-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_remove_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
